GET http://localhost:3310/api/gamecharacter HTTP/1.1

###

GET http://localhost:3310/api/gamecharacter/2 HTTP/1.1

###

POST http://localhost:3310/api/gamecharacter HTTP/1.1
content-type: application/json

{
  "name": "Grimm",
  "role": "allié", 
  "image": "osef",
  "status": "vivant", 
  "vitalPoints": 40, 
  "manaPoints": 15, 
  "initiativeScore": 22, 
  "description": "Chef de la garde d'Hamersprit"
}

###

PUT http://localhost:3310/api/gamecharacter/3 HTTP/1.1
content-type: application/json

{
  "name": "Gorgonzolla",
  "role": "allié", 
  "image": "osef",
  "status": "vivant", 
  "vitalPoints": 40, 
  "manaPoints": 15, 
  "initiativeScore": 22, 
  "description": "Chef de la garde d'Hamersprit"
}

###

DELETE http://localhost:3310/api/gamecharacter/4 HTTP/1.1

###
GET http://localhost:3310/api/user HTTP/1.1

###

POST http://localhost:3310/api/user HTTP/1.1
content-type: application/json

{
  "mail": "jc@mail.com",
  "password": "Pouet123!", 
  "nickname": "Mufufu"
}

###

POST http://localhost:3310/api/user/login HTTP/1.1
content-type: application/json

{
  "mail": "mail@mail.mail",
  "password": "123"
}